development:
  adapter: postgresql
  encoding: utf8
  database: remisse
  pool: 5
  username: anibalcucco
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: remisse_test
  pool: 5
  username: anibalcucco
  password:
