development:
  adapter: postgresql
  encoding: utf8
  database: remisse
  pool: 5
  username: anibal
  password: anibal

test:
  adapter: postgresql
  encoding: utf8
  database: remisse_test
  pool: 5
  username: anibal
  password: anibal
