development:
  adapter: mysql2
  encoding: utf8
  database: remisse
  host: 127.0.0.1
  port: 3306
  pool: 5
  username: root
  password:
  socket: /var/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  database: remisse_test
  pool: 5
  username: root
  password:
  socket: /var/mysql/mysql.sock
